%% Assignment 1: Introduction to System Identification
%  [WB2301] SIPE

%% Question 1: Signal generation
% You can generate the signal by calling the |sim()| command directly from
% the command line. You can then use the command |whos| to see which variables
% were created in the workspace. Note the difference between variables |t|
% and |tout|. Variable |tout| is automatically generated by Simulink and it
% holds the time instances used in evaluating the model. Variable |t| holds
% the sample times at the sampling rate stated in the model.
% So: Simulink uses a higher sample rate internally for obtaining
% accurate results, while we use sampling to obtain a time vector with a
% fixed sample rate of 100 Hz.
clear all
close all
clc

T   = 5;                % [s] Observation time
fs  = 100;              % [Hz] Samping frequency
dt  = 1/fs;             % [s] Sample time
set_param('Ass1_System/Noise n', 'Variance', '0');
sim('Ass1_System',T)    % Note that observation stop time and sample frequency are set in the model.

% Observation time T = N * dt. The last sample of the measured signals
% needs to be removed in order to make the observation time exactly 5
% seconds.
N = length(u);                % [-] # samples (also T /dt)
t = (0 : N - 1) * dt;         % [s] Time vector

% Plot input and output signals.
figure
subplot(211); plot(t, u, 'linewidth', 2);
xlabel('t [s]', 'Fontsize', 18); ylabel('u [-]', 'Fontsize', 18);
title('Input', 'Fontsize', 20)
set(gca,'FontSize',18)
subplot(212); plot(t, y, 'linewidth', 2);
xlabel('t [s]', 'Fontsize', 18); ylabel('y [-]', 'Fontsize', 18);
title('Output', 'Fontsize', 20)
set(gca, 'FontSize', 18)
eps_save('question1')


%% Question 1a

[Cuu, lags] = xcov(u, u, 'biased');
Cuy = xcov(u, y, 'biased');
Cyu = xcov(y, u, 'biased');
Cyy = xcov(y, y, 'biased');
tau = lags * dt; % Fill in the dots  [lags should be in seconds]

% Plot the covariances in one figure using subplot
figure('Name','Question 1a')
subplot(2,2,1)
    plot(tau, Cuu, 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{uu}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
subplot(2,2,2)
    plot(tau, Cuy, 'linewidth', 2);
    xlabel('tau  [s]', 'Fontsize', 18); ylabel('C_{uy}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
subplot(2,2,3)
    plot(tau, Cyu, 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{yu}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
subplot(2,2,4)
    plot(tau, Cyy, 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{yy}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
eps_save('question1a')


%% Question 1d

Cyu_unbiased = xcov(y, u, 'unbiased');
figure('Name', 'Question 1d')
    plot(tau, Cyu, 'b', tau, Cyu_unbiased, 'g', 'linewidth', 2)
    legend('biased', 'unbiased')
    xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{yu}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
eps_save('question1d')

 %% Question 1f

 Kuu = Cuu / sqrt(var(u)*var(u));
 Kyu = Cyu / sqrt(var(u)*var(y));

figure('Name','Question 1f')
subplot(2,1,1)
    plot(tau, Kuu, 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18); ylabel('K_{uu}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
subplot(2,1,2)
    plot(tau, Kyu, 'linewidth', 2);
    xlabel('tau  [s]', 'Fontsize', 18); ylabel('K_{yu}', 'Fontsize', 18)
    set(gca, 'FontSize', 18)
eps_save('question1d')

[Kuu_max, Kuu_argmax] = max(Kuu, [], 1);
[Kyu_max, Kyu_argmax] = max(Kyu, [], 1);
Kuu_argmax_tau = tau(Kuu_argmax)
Kyu_argmax_tau = tau(Kyu_argmax)

%% Question 1g

% figure('Name','Question 1g,(biased)')
% subplot(4,1,1)
%     plot(tau, xcov(u, u, 'biased'), 'b',  tau, crosscov(u, u, 'biased'), 'g');
%     xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{uu}', 'Fontsize', 18)
% subplot(4,1,2)
%     plot(tau, xcov(u, y, 'biased'), 'b', tau, crosscov(u, y, 'biased'), 'g');
%     xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{uy}', 'Fontsize', 18)
%  subplot(4,1,3)
%     plot(tau, xcov(y, u, 'biased'), 'b', tau, crosscov(y, u, 'biased'), 'g');
%     xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{yu}', 'Fontsize', 18)
% subplot(4,1,4)
%     plot(tau, xcov(y, y, 'biased'), 'b', tau, crosscov(y, y, 'biased'), 'g');
%     xlabel('lag [s]', 'Fontsize', 18); ylabel('C_{yy}', 'Fontsize', 18)
e_uu = xcov(u, u, 'biased') - crosscov(u, u, 'biased');
e_uy = xcov(u, y, 'biased') - crosscov(u, y, 'biased');
e_yu = xcov(y, u, 'biased') - crosscov(y, u, 'biased');
e_yy = xcov(y, y, 'biased') - crosscov(y, y, 'biased');
dot(e_uu, e_uu)
dot(e_uy, e_uy)
dot(e_yu, e_yu)
dot(e_yy, e_yy)

e_uu = xcov(u, u, 'unbiased') - crosscov(u, u, 'unbiased');
e_uy = xcov(u, y, 'unbiased') - crosscov(u, y, 'unbiased');
e_yu = xcov(y, u, 'unbiased') - crosscov(y, u, 'unbiased');
e_yy = xcov(y, y, 'unbiased') - crosscov(y, y, 'unbiased');
dot(e_uu, e_uu)
dot(e_uy, e_uy)
dot(e_yu, e_yu)
dot(e_yy, e_yy)

%% Question 1h
H = tf(1, [0.01, 0.03, 1]);
[y_impulse, t_impulse] = impulse(H, t);
figure('Name','Question 1h')
    plot(t_impulse, y_impulse, 'b', tau, Cyu, 'g', 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18);
    ylabel('impulse response, C_{yu}', 'Fontsize', 18)
    legend('impulse response of H', 'C_{yu}')
    set(gca, 'FontSize', 18)
eps_save('question1h')

%% Question 1i
sim('Ass1_System', 100)    % Note that observation stop time and sample frequency are set in the model.
N   = length(u);                % [-] # samples (also T /dt)
t   = (0 : N - 1) * dt;         % [s] Time vector

[Cyu100, lags100] = xcov(y, u, 'biased');
figure('Name','Question 1i')
    plot(t_impulse, y_impulse, 'b', tau, Cyu, 'g',...
        lags100*dt, Cyu100, 'r', 'linewidth', 2);
    xlabel('lag [s]', 'Fontsize', 18);
    ylabel('impulse response, C_{yu}, C_{yu100}', 'Fontsize', 18)
    legend('impulse response of H', 'C_{yu}', 'C_{yu100}')
    set(gca, 'FontSize', 18)
eps_save('question1i')

%% Question 2a
clear all
close all
clc

fs = 500;
dt = 1/fs;
T = 5;
t = 0:dt:T-dt;
f_sig = 8; % Hz

u = 2*sin(2*pi*f_sig*t) + normrnd(0, 1, size(t));

[B, A] = butter(2, 20/(fs/2));
y = filter(B, A, u);
h = plot(t, u, 'b', t, y, 'r');
    set(h(1),'linewidth',1);
    set(h(2),'linewidth',4);
Y = fft(y);
f = t/T*fs;
figure('Name', 'Question 2a')
subplot(2, 1, 1)
    plot(f, abs(Y), 'linewidth', 2)
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('|Y(f)|', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
subplot(2, 1, 2)
    plot(f, phase(Y), 'linewidth', 2)
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('phase(Y(f)) [deg]', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
eps_save('question2a')

%% Question 2b
clear all
close all
clc

T = 5; % [s] Observation time
fs = 100; % [Hz] Samping frequency
dt = 1/fs; % [s] Sample time
sim('Ass1_System',T)
% observation stop time and sample frequency are set in the model.

% Observation time T = N * dt. The last sample of the measured signals
% needs to be removed in order to make the observation time exactly 5
% seconds.
N = length(u);                % [-] # samples (also T /dt)
t = (0 : N - 1) * dt;         % [s] Time vector

U = fft(u);
Y = fft(y);
f = t/T*fs;
Suu = U.*conj(U)/length(u);
Syu = Y.*conj(U)/length(u);
figure('Name', 'Question 2b');
subplot(2, 1, 1)
    loglog(f, abs(Suu), 'linewidth', 2)
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('|Suu(f)|', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
subplot(2, 1, 2)
    loglog(f, abs(Syu), 'linewidth', 2)
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('|Syu(f)|', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
eps_save('question2b')

%% Question 2c
[Cuu, lags] = xcov(u, u, 'biased');
Suu_bias = fft(Cuu);
Syu_bias = fft(xcov(y, u, 'biased'));
Suu_unb = fft(xcov(u, u, 'unbiased'));
Syu_unb = fft(xcov(y, u, 'unbiased'));
f = (0:2*(N - 1))/T;
figure('Name', 'Question 2c')
subplot(2, 1, 1)
    loglog(f, abs(Suu_bias), 'b', f, abs(Suu_unb), 'g', 'linewidth', 2)
    legend('biased', 'unbiased')
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('|Suu(f)|', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
subplot(2, 1, 2)
    loglog(f, abs(Syu_bias), 'b', f, abs(Syu_unb), 'g', 'linewidth', 2)
    legend('biased', 'unbiased')
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('|Syu(f)|', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
eps_save('question2c')

% not sure about this
figure()
size(Suu)
loglog(t/T*fs, abs(Suu), 'b', f, abs(Suu_bias), 'g')

%% Question 3: Time Domain Models
clear all
close all
clc

% Create data
T = 50;               % [s] Observation time
fs = 100;              % [Hz] Samping frequency
dt = 1/fs;             % [s]
N = fs*T;             % [-] Number of samples
tv = (0:N-1).'/fs;     % Time vector
fv = (0:N-1)/N*fs;     % Frequency vector

% Simulate model
set_param('Ass1_System/Noise n', 'Variance', '0.05');
% only produce output for the time values in vector <t>
options = simset('OutputPoints', 'specified');
load_system('Ass1_System')
sim('Ass1_System', tv, options)

%% Question 3a
% Generate iddata structure
dat = iddata(y, u, dt);
set(dat, 'timeunit', 's', 'inputname', 'u', 'outputname', 'y');
% figure(); plot(dat)
%%
na = 12;
nb = 12;
nk = 0;
sys = arx(dat, [na, nb, nk]);
n_half = length(fv)/2;
if n_half == ceil(n_half)
    fv_half = fv(1:n_half + 1);
else
    fv_half = fv(1:ceil(n_half));
end
H = squeeze(freqresp(sys, fv_half, 'Hz'));
sys_true = tf(1, [0.01, 0.03, 1]);
H_true = squeeze(freqresp(sys_true, fv_half, 'Hz'));
figure('Name', 'Question 3a')
system_legend = {'True', 'ARX'};
%cmap = hsv(length(system_legend));
subplot(2, 1, 1)
    hold on
    %plot(fv_half, abs(H_true), 'color', cmap(1, :), 'linewidth', 2)
    %plot(fv_half, abs(H), 'color', cmap(2, :), 'linewidth', 2)
    plot(fv_half, abs(H_true), 'color', 'b', 'linewidth', 2)
    plot(fv_half, abs(H), 'color', 'g', 'linewidth', 2)
    hold off
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('gain', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
	legend(system_legend);
subplot(2, 1, 2)
    hold on
    plot(fv_half, phase(H_true), 'color', 'b', 'linewidth', 2)
    plot(fv_half, phase(H), 'color', 'g', 'linewidth', 2)
    hold off
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('phase [deg]', 'Fontsize', 18);
    set(gca, 'FontSize', 18)
	legend(system_legend);
eps_save('question3a')

%% Question 3c

sys_oe = oe(dat, [3, 3, 0]);
sys_arx = arx(dat, [3, 3, 0]);
% sys_arma = armax(dat, [3, 3, 0, 0]);
sys_armax = armax(dat, [3, 3, 3, 0]);
sys_bj = bj(dat, [3, 3, 3, 3, 0]);
sys_true = tf(1, [0.01, 0.03, 1]);

% systems = {sys_oe, sys_arx, sys_arma, sys_armax, sys_bj, sys_true};
% system_legend = {'OE', 'ARX', 'ARMA', 'ARMAX', 'BJ', 'True'};
% systems = {sys_true, sys_oe, sys_arx, sys_armax, sys_bj};
systems = {sys_true, sys_oe};
% system_legend = {'True', 'OE', 'ARX', 'ARMAX', 'BJ'};
system_legend = {'True', 'OE'};
H = cell(size(systems));
%cmap = hsv(length(systems));
cmap = {'b', 'g'};
fit = zeros(size(systems));

figure(1); clf
for i = 1:length(systems)
    H{i} = squeeze(freqresp(systems{i}, fv_half, 'Hz'));

    subplot(211)
    hold on;
    loglog(fv_half, abs(H{i}), cmap{i}, 'linewidth', 2);
    hold off
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('gain', 'Fontsize', 18);
    if i == length(systems)
        legend(system_legend);
        set(gca, 'FontSize', 18)
    end

    subplot(212)
    hold on;
    semilogx(fv_half, phase(H{i}), cmap{i}, 'linewidth', 2);
    hold off
    xlabel('frequency [Hz]', 'Fontsize', 18);
    ylabel('phase [deg]', 'Fontsize', 18);
    if i == length(systems)
        legend(system_legend);
        set(gca, 'FontSize', 18);
        set(gcf, 'Name','Question 3c');
    end

    [y, fit(i), x0] = compare(dat, systems{i});
end
eps_save('question3c')
